name: build

on:
  push:
    branches:
      - master

env:
  HUSKY: 0

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - run: pip install pipenv
      - run: pipenv install
      - run: npm install
      - run: pipenv run python sprite.py
      - run: npm run build:dist
      - run: npx semantic-release
  gh-pages:
    name: gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - run: pip install pipenv
      - run: pipenv install
      - run: npm install
      - run: pipenv run python sprite.py
      - run: npm run build
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: examples/public
